FROM debian:latest

RUN apt-get update && apt-get install -y \
  ca-certificates \
  libcurl4-gnutls-dev \
  pkg-config \
  libssl-dev \
  wget \
  curl \
  libc-client2007e-dev \
  libbz2-dev \
  libjpeg-dev \
  libmcrypt-dev \
  libxslt1-dev \
  libxslt1.1 \
  libpq-dev \
  build-essential \
  git \
  make

RUN wget http://php.net/distributions/php-7.0.28.tar.gz
RUN tar xvf php-7.0.28.tar.gz
RUN ./php-7.0.28/configure \
--prefix=/opt/php-7.0.28                      \
--with-config-file-path=/opt/php-7.0.28/etc   \
--with-freetype-dir                          \
--enable-mbstring                            \
--with-libxml-dir=/usr                       \
--enable-calendar                            \
--with-curl                                  \
--with-mcrypt                                \
--disable-rpath                              \
--enable-inline-optimization                 \
--enable-sockets                             \
--enable-sysvsem                             \
--enable-sysvshm                             \
--enable-pcntl                               \
--enable-mbregex                             \
--enable-exif                                \
--enable-bcmath                              \
--with-mhash                                 \
--with-pcre-regex                            \
--with-openssl                               \
--with-fpm-user=www-data                     \
--with-fpm-group=www-data                    \
--with-imap                                  \
--with-imap-ssl                              \
--with-gettext                               \
--with-xsl                                   \
--enable-opcache                             \
--enable-fpm
RUN make
RUN make install

RUN pecl install mailparse
