FROM debian:latest

RUN apt-get update && apt-get install -y \
  ca-certificates \
  libcurl4-gnutls-dev \
  pkg-config \
  libssl-dev \
  wget \
  curl \
  libc-client2007e-dev \
  libbz2-dev \
  libjpeg-dev \
  libmcrypt-dev \
  libxslt1-dev \
  libxslt1.1 \
  libpq-dev \
  libzip-dev \
  libzip4 \
  build-essential \
  git \
  make

RUN wget http://php.net/distributions/php-7.0.28.tar.gz
RUN tar xvf php-7.0.28.tar.gz
RUN ./php-7.0.28/configure --prefix=/opt/php-7.0.28 \
    --enable-bcmath \
    --enable-fpm \
    --with-fpm-user=www-data \
    --with-fpm-group=www-data \
    --enable-mbstring \
    --enable-phpdbg \
    --enable-shmop \
    --enable-sockets \
    --enable-sysvmsg \
    --enable-sysvsem \
    --enable-sysvshm \
    --enable-zip \
    --with-libzip=/usr/lib/x86_64-linux-gnu \
    --with-zlib \
    --with-curl \
    --with-pear \
    --with-openssl \
    --enable-pcntl \
    --with-readline
RUN make
RUN make install

RUN pecl install mailparse
